### ISSUE TITLE
Create Playlist component UI

### ISSUE THREAD

**Issue by adamjarling** [samvera-labs/iiif-react-media-player#1]
### Description
Need to recreate the "Playlists" UI feature from Avalon Media system, into an isolated component in this code repository.

Screenshot of the current playlists look in Avalon:

![Screenshot from 2020-11-05 09-49-20](https://user-images.githubusercontent.com/1331659/98256227-4d500f00-1f4c-11eb-9021-9b4c38ea7d00.png)

To see playlists in action see [this playlist](https://spruce.dlib.indiana.edu/playlists/267?token=nrx9org8J79R1VqHnj0JhA) in one of Avalon's test servers.

### Done looks like
- [ ] Playlist items UI created

### Notes
This depends on how IIIF manifests model playlists.

**Comment by joncameron** [comment]
https://github.com/avalonmediasystem/avalon/issues/4222
