### ISSUE TITLE
Standalone version of IIIF media player

### ISSUE THREAD

**Issue by elynema** [samvera-labs/iiif-react-media-player#145]
Useful to IIIF community to have a standalone interactive version of the IIIF media player that allows users to enter URLs for manifests, just like the Timeliner demo at https://timeliner.dlib.indiana.edu. This helps with testing different cookbook recipes and also allowing community members to experiment with building and playing AV manifests.

Current [IIIF player site](https://samvera-labs.github.io/iiif-react-media-player/) demonstrates use of components, but requires code editing to bring up a new manifest in the player.

# Done Criteria
- [x] Identify a hostname / place to host
- [x] Determine if an automated deploy pipeline is needed
- [x] Player provides an interactive way for users to enter a manifest URL or upload a manifest

# Notes
A Heroku plugin is currently used for the SME demo site as part of moving manifest examples from the dlib sites. Could be a potential avenue for setting up a demo site instance that's Github hosted rather than dlib hosted.

- https://fixtures.iiif.io/

**Comment by joncameron** [comment]
Could this be hosted using the same means as the SME?
