### ISSUE TITLE
Highlight structured navigation time window on player

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/iiif-react-media-player#19]
### Description

When using structured navigation highlight the time fragment selected on the player time rail.

![Screenshot from 2020-11-13 16-43-56](https://user-images.githubusercontent.com/1331659/99124071-76694300-25cf-11eb-9808-4a5d551f2f8f.png)

**Comment by phuongdh** [comment]
![image](https://user-images.githubusercontent.com/1304657/99709595-689f3c00-2a6d-11eb-92b5-8c0b2a5e4cc0.png)
