### ISSUE TITLE
Update time rail highlight as the player time updates

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/iiif-react-media-player#56]
**Is your feature request related to a problem? Please describe.**

The player's time can be updated in 3 ways:
1. Using structure navigation
2. As the player keeps on playing naturally
3. User seeking to a specific point of time using the playhead

For all these scenarios the time rail must get highlighted if the current time of the playhead falls within a defined structure item's range. This works when using the structure navigation, but not in the other 2 scenarios.
The time rail highlight stays at the same place where it was last updated through structure navigation as shown in the following screenshot;
![Screenshot from 2020-12-10 09-36-30](https://user-images.githubusercontent.com/1331659/101785849-3f515900-3acb-11eb-84b9-15f0216c2786.png)
Here the time fragment of the last clicked structure item is highlighted in the player while the playhead has kept progressing. 

**Describe the solution you'd like**
Keeping consistent with the old player, there are 2 scenarios to consider when implementing a solution to this.
1. When the current time of the playhead falls within a defined structure item's time fragment: highlight that relevant fragment in the player.
2. When it's outside of defined structure (there could be ranges with undefined structure): remove the time rail highlighter.

**Comment by joncameron** [comment]
We'll need to investigate rendering fragments in the time rail in Video.js (what are the options to implement?)

**Comment by Dananji** [comment]
In the current implementation the time rail gets highlighted only through structure navigation, not through the other 2 ways. Therefore changing the estimate back to 3 from 2.
