### ISSUE TITLE
Transcripts component wireframe implementation

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/iiif-react-media-player#70]
### Description

Transcript UI component is designed and ready to be wired up with the player and structure navigation components

### Done Looks Like

- [x] Finalized design of the transcript component
- [x] CSS and JSX codes written for the component
- [x] Component is designed in a way it can be placed in different places with respect to the other component in different layouts

**Comment by joncameron** [comment]
Merged to github demo page and ready to be tested
