### ISSUE TITLE
Add keyboard shortcuts to player

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/iiif-react-media-player#75]
### Description

Most media players nowadays have keyboard shortcuts. The basic ones are as follows;

- Exit/enter full-screen - `f`

- Mute/un-mute - `m`

- Play/pause - `space-bar`

- Increase/decrease volume - `up/down arrow keys`

- Jump forward/backwards in playback - `right/left arrow keys`

### Done Looks Like

The player functions work with the key presses listed above.

### Notes

VideoJS plugin that can be used: https://github.com/ctd1500/videojs-hotkeys

**Comment by Dananji** [comment]
Test here: https://samvera-labs.github.io/iiif-react-media-player/

**Comment by joncameron** [comment]
Works great!
