### ISSUE TITLE
Add create thumbnail component or service

### ISSUE THREAD

**Issue by adamjarling** [samvera-labs/iiif-react-media-player#8]
### Description

Add `Create Thumbnail` support for video in iiif player like in avalon player;
![Screenshot from 2020-03-02 14-51-03.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/90642de7-9012-43b1-a385-31f85d6cfb18)

### Done Looks Like

- [ ] player allows users to create thumbnail for video

**Comment by adamjarling** [comment]
@Dananji Mind adding a link to a public Avalon player which supports this and we can get a live example?

**Comment by Dananji** [comment]
Thumbnail creation feature is available only to logged in users, so to see this in action one has to create an account and login. So if someone likes to see it action please go to this [link](https://spruce.dlib.indiana.edu), and create an account. Then go to [this item](https://spruce.dlib.indiana.edu/media_objects/pz50gw27b) and see how this feature works in Avalon.

For anyone who wants to see a demo of this, I've added the following GIF. And I apologize for the bad quality in advance.
The steps followed in this video are;
1. Seek to the frame which we want to create the thumbnail out of
2. Click on the `Create Thumbnail` button
3. See the preview in pop-up window, and set it
4. Reload page to see the new thumbnail

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/1331659/98565793-06c82080-227c-11eb-9bec-ba12e55d5566.gif)
