### ISSUE TITLE
Move CSS for structure navigation

### ISSUE THREAD

**Issue by Dananji** [samvera-labs/iiif-react-media-player#83]
### Description

Currently the CSS for indicating the active item in the structure is within the `StructuredNavigation.scss` file which is not getting bundled up in the package. So when you use this component in a host application, structure navigation is not properly visible like below, where the current playing item in the structure is `Rinsing Well` item, which cannot be seen in the structured navigation component.

![Screenshot from 2021-05-21 12-19-38.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/e14fe7c5-d304-475a-ab6e-dc88e86fd3c3)

### Done Looks Like

CSS for the arrow pointer is included in the main css, which gets bundled. So that, the structure navigation component displays the current item that's being played.
![Screenshot from 2021-05-21 13-34-42.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/5deb5653-4fe0-416c-88e7-9c41aa14ce34)

**Comment by joncameron** [comment]
This should be in a patch release, since it's impacting installs since there's no styling.

**Comment by Dananji** [comment]
This can be tested after the beta release (#90)
